frontend/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views


app_name = 'frontend'
urlpatterns = [
    path('', views.home, name='home'),
    path('todayLedger/', views.todayLedger, name='todayLedger'),
    path('<int:pk>/', views.updateItem, name='itemComplete'),
    path('<int:pk>/update/', views.ItemUpdate.as_view(), name='itemUpdate'),
    path('<int:pk>/delete/', views.ItemDelete.as_view(), name='itemDelete'),
]

yaymont/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('frontend.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
] +  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

frontend/models.py
from django.db import models

# Create your models here.

ordering/models.py
from django.db import models
from django.urls import reverse
# Create your models here.


class IntegerRangeField(models.IntegerField):
    def __init__(self, verbose_name=None, name=None, min_value=None, max_value=None, **kwargs):
        self.min_value, self.max_value = min_value, max_value
        models.IntegerField.__init__(self, verbose_name, name, **kwargs)
    def formfield(self, **kwargs):
        defaults = {'min_value': self.min_value, 'max_value':self.max_value}
        defaults.update(kwargs)
        return super(IntegerRangeField, self).formfield(**defaults)

    

class Ordering(models.Model):
    YMONT_TYPES = [
        ('S', 'ရိုးရိုး'),
        ('E', 'ကြက်ဉ'),
        ]
    
    order_id = models.AutoField(primary_key=True)
    p_type = models.CharField(
        'ရိုးရိုး လား ကြက်ဉလား',
        max_length=1,
        choices=YMONT_TYPES,
        default='S',
        help_text="Simple or Egg ?",
    )
    p_count = IntegerRangeField('အရေအတွက်',default=1, min_value=1, max_value=15,help_text="How Many ?")
    name = models.CharField('နာမည်အပြည့်အစုံ', max_length=120, help_text="နာမည်ဖြည့်ပါ")
    phone = models.CharField('ဖုန်းနံပါတ်', max_length=13, help_text="ဖုန်းနံပါတ်ထည့်ပေးပါ")
    completed = models.BooleanField(default=False)
    pub_date = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('frontend:itemUpdate', kwargs={'pk':self.order_id})

ordering/forms.py
from django import forms
from .models import Ordering

class OrderForm(forms.ModelForm):
    class Meta:
        model = Ordering
        fields = '__all__'
        exclude = ['order_id', 'time', 'completed']

frontend/views.py
from django.shortcuts import render, redirect
from ordering.models import Ordering
from ordering.forms import OrderForm
import datetime

from django.urls import reverse_lazy
from django.views.generic.edit import DeleteView, UpdateView
from django.views.generic.detail import DetailView    
from django.contrib.auth.decorators import login_required


# Create your views here.

def home(request):
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('frontend:home')

    else:
        form = OrderForm()
            
    orders = Ordering.objects.filter(completed=False)
    
    return render(request, 'frontend/index.html', {
        'allorders': orders,
        'form': form,
        } )
        

@login_required(login_url='login')
def updateItem(request, pk):
	obj = Ordering.objects.get(pk=pk)
	obj.completed = True
	obj.save()
	return redirect('frontend:home')
	


@login_required(login_url='login')
def todayLedger(request):
	totalEgg = Ordering.objects.filter(pub_date__date=datetime.date.today() ).filter(completed=True).filter(p_type='E')
	totalSimple = Ordering.objects.filter(pub_date__date=datetime.date.today() ).filter(completed=True).filter(p_type='S')
	DailyList = Ordering.objects.filter(pub_date__date=datetime.date.today() ).filter(completed=True)
	return render(request, 'frontend/daily_report.html', 
	{'dailylist': DailyList,
		'totalEgg': totalEgg,
		'totalSimple': totalSimple,
	})


class ItemDelete(DeleteView):
	model = Ordering
	success_url = reverse_lazy('frontend:home')



class ItemUpdate(UpdateView):
	model = Ordering
	fields = ['name','phone', 'p_type', 'p_count', 'completed']
	success_url = reverse_lazy('frontend:home')
	template_name_suffix = '_update_form'
	

ordering/views.py
from django.shortcuts import render

# Create your views here.

frontend/templates/frontend/daily_report.html
{% extends 'master.html' %}
{% load static %}

{% block Hscript %}
  <script type="text/javascript" src="{% static 'frontend/js/loader.chart.js' %}"></script>
  
  <div class="">
	{% for Egg in totalEgg %}
		<span class="eggCount" id="{{Egg.p_count}}"></span>
	{% endfor %}
  </div>
  
    <div class="">
	{% for Simple in totalSimple %}
		<span class="simpleCount" id="{{Simple.p_count}}"></span>
	{% endfor %}
  </div>
  
  
    <script type="text/javascript">
      google.charts.load('current', {'packages':['corechart']});
      google.charts.setOnLoadCallback(drawChart);

      function drawChart() {
		  let Eggtotal = 0;
  $('.eggCount').each(function() {
  Eggtotal +=  parseInt(this.id, 10);
  });
  $('#eggSell').html(Eggtotal);
  $('#eggSellTotal').html(Eggtotal * 400 +" ကျပ်");
 
  let Simpletotal = 0;
  $('.simpleCount').each(function() {
  Simpletotal +=  parseInt(this.id, 10);
  });
  $('#simpleSell').html(Simpletotal);
  $('#simpleSellTotal').html(Simpletotal * 200 +" ကျပ်");
        var data = google.visualization.arrayToDataTable([
          ['Task', 'Hours per Day'],
          ['ရိုးရိုး',     Simpletotal],
          ['ကြက်ဉ',      Eggtotal],
        ]);

        var options = {
          title: ''
        };

        var chart = new google.visualization.PieChart(document.getElementById('piechart'));

        chart.draw(data, options);
      }
    </script>
{% endblock %}

{% block content %}
	<div class='container'>
		<h5 style="margin-top: 15px;">ယနေ့ ရောင်းချမှုဇယား</h5>
		<div id="piechart" style="width: 320px; height: auto;"></div>
		
		
		<div class="myRow">
			<div class="one-third-column" style="box-shadow:none;">
			 ရိုးရိုး : <span id='simpleSell'></span> ခု  <br>
			 ပေါင်း : <strong id='simpleSellTotal'> </strong>
			</div>
			<div class="one-third-column" style="box-shadow:none;">
			ကြက်ဉ : <span id='eggSell'></span> ခု <br>
			ပေါင်း : <strong id='eggSellTotal'></strong>
			</div>
			
		</div>
		<hr>
		

		<div class="container">
		
		<table class="u-full-width">
		<thead>
			<tr>
				<th> နာမည် </th>
				<th> အမျိုးအစား</th>
				<th style="text-align: center;"> အခု ရေ</th>
				
			</tr>
		</thead>
		<tbody>
			{% for order in dailylist %}
				<tr>
					<td><a style="color: #333;" href="{% url 'frontend:itemUpdate' order.order_id %}">{{order.name}}</a></td>
										<td>  	{% if order.p_type == 'E' %} 
								<strong style="color: orange;"> ကြက်ဉ 
							{% else %} <strong> ရိုးရိုး{% endif %} </strong>
					</td>
					<td style="text-align: center;" class="ycount" id="{{order.p_count}}">{{order.p_count}}</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
		
		</div>
	</div>
	<style>
	#eggSell, #simpleSell{
		padding: 5px;
		font-size: 18px;
		font-weight: bold;
		}
	</style>
{% endblock %}

frontend/templates/frontend/index.html
{% extends 'master.html' %}
{% load static %}
{% block content %}
  <div class="container" style="margin-top:10px;" >
	 {% if user.is_authenticated %}
	 <a href="{% url 'frontend:todayLedger'%}" class="button">ပြန်စစ်</a>
	 {% else %}
    <a href="tel:09260054792" class="button">09260054792</a>
    {% endif %}
	  <button onClick="location.reload()" style="float:right;" class="button button-primary"> Refresh 
		{% if user.is_authenticated %}
	  (<span id='tminus'> 30 </span>)
	  <script> setInterval(()=>{ t = parseInt($('#tminus').text(), 10); t--;  $('#tminus').html(t); },1000); </script></button>
	  {% endif %}
  </div>
  

  <!-- Primary Page Layout
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <div class="container">
	  
    <div class="row">
      <div class="one-half column">
        <h5>ရေမုန့်  ကြိုမှာထားသည့်စာရင်း</h5>
        <h6 style="text-align:right;color: gold;"> ဆိုင်ဖွင့်ချိန် (နေ့လည် ၂နာရီ)</h6>
	{% if not user.is_authenticated %}
	<div style="padding:15px;padding-bottom:0px; margin-bottom: 15px; background: #fff; box-shadow: 0px 1px 5px #ccc;">
	<div class="row">
	  <div class="columns" style="width: 45%; text-align: center;">
	    <img width=100 height=100 src="{% static 'frontend/images/simple.jpg' %}" alt="Simple Yaymont" />
	    <h6> ရိုးရိုး = 200 ကျပ် </h6>
	  </div>
	  
	  <div class="columns" style="width: 45%; text-align: center;">
	    <img width=100 height=100 src="{% static 'frontend/images/egg.jpg' %}" alt="Egg Plus"/>
	    <h6> ကြက်ဉနဲ့ = 400 ကျပ် </h6>
	  </div>
	</div>
	</div>  
	{% endif %}
	
	  {% if user.is_authenticated %}
	<table class="u-full-width" >
		<thead>
			<tr>
				<th> နာမည် </th>
				<th> အမျိုး </th>
				<th> အခု </th>
				<th> လုပ်ဆောင်</th>
			</tr>
		</thead>
		<tbody>
			{% for order in allorders %}
				<tr>
					<td><a style="color: #333;" href="{% url 'frontend:itemUpdate' order.order_id %}">{{order.name}}</a></td>
					<td>  	{% if order.p_type == 'E' %} 
								<strong style="color: orange;"> ကြက်ဉ 
							{% else %} <strong> ရိုးရိုး{% endif %} </strong>
					</td>
					<td class="ycount" id="{{order.p_count}}">{{order.p_count}}</td>
					<td><a onClick="orderComplete('{% url 'frontend:itemComplete' order.order_id%}')" 
							style="cursor: pointer; padding:5px; border:1px solid; border-radius:5px;background: green;color: #fff;">ပြီးပြီ</a> 
						<a href="{% url 'frontend:itemDelete' order.order_id %}" style="color: red;padding: 10x;">ဖျက်</a></td>
				</tr>
			{% endfor %}
		</tbody>
	</table>

	  {% else %}
	  <ul>
	    {% for order in allorders %}
	    <li style="font-size: 14px; text-decoration:underline;" class="ycount" id="{{order.p_count}}"> 
			{{order.p_count}} Item{% if order.p_count > 1 %}s{%endif%}  </li> 
	    {% endfor %}
	  </ul>
	  {% endif %}
	<p style="font-size: 16px;text-align:right; padding: 5px; border:1px solid #333; border-radius: 5px;">
	  စောင့်ရမည့်အရေအတွက် : <span id="tcount" style="font-size: 34px;"></span> ခု<br>

	</p>   
	<hr>
      </div>

      <div class="one-half column">
		 
	<h5> <strong>အောက်ကဖောင်ဖြည့်ပြီး ကြိုမှာထားလို့ရပြီ  </strong></h5>

	<form action="{% url 'frontend:home' %}" method="post" id="orderF">
	  {%csrf_token%}
	  {{form.as_ul}} <br>
	  <input class="button button-primary" type="submit"  value="Submit">
	</form>

      </div>
      
    </div>
  </div>
{% endblock %}

{% block Cscript %}

<script>

  
  function orderComplete(completeURL){
	  var r = confirm('ပြီးတာသေချာပြီလား');
	  
	  if(r == true){
		window.location.href = completeURL;  
	  }else{
		
		}
  };
  
  function setAlter(){
	  
	  }
</script>
{% endblock %}

frontend/templates/master.html
<!DOCTYPE html>
<html lang="en">
<head>
  
  <!-- Basic Page Needs
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta charset="utf-8">
  <title>YayMont Order</title>
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- Mobile Specific Metas
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- FONT
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link href="//fonts.googleapis.com/css?family=Raleway:400,300,600" rel="stylesheet" type="text/css">

  <!-- CSS
       –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'frontend/css/normalize.css' %}">
  <link rel="stylesheet" href="{% static 'frontend/css/skeleton.css' %}">

  <!-- Favicon
       –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  
  <link rel="icon" type="image/png" href="{% static 'frontend/images/favicon.png' %}">
	{% block Hscript %} {% endblock %}
</head>
<body onload="showtotal()">
	<div class="mainWrap">
		{% block content %}{% endblock %}
	</div>
	{% if user.is_authenticated %}
	<div class="admin-helper">
		<div class="myRow">
			<div class="one-third-column">
				<a href="{% url 'frontend:home' %}">အော်ဒါ</a>
			</div>
			<div class="one-third-column">
				<a href="{% url 'frontend:todayLedger'%}">နေ့စဉ်</a>
			</div>
			<div class="one-third-column">
				<a href="">ဆိုင်ပြင်</a>
			</div>
		</div>
	</div>
	{% endif %}
</body>
<script
			  src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
			  crossorigin="anonymous"></script>

  {% block Cscript %}<!-- default content text (typically empty) -->{% endblock %}
  
  <script>
    function showtotal(){
  let total = 0;
  $('.ycount').each(function() {
  total +=  parseInt(this.id, 10);
  });
  $('#tcount').html(total);
  {% if user.is_authenticated %}
	setTimeout(()=>{ location.reload(); }, 30000);
  {% endif %}
    
  };
  </script>
<style>
  #orderF{
  border:1px solid #ddd;
  padding:30px;
  
  }
  .admin-helper{
	  position: fixed;
	  bottom: 0px;
	  left:0;
	  right: 0;
	  z-index: 9;
	  background: #fafafa;
	  box-shadow: 1px 0px 3px #ccc;
  }
  .myRow{
		position: relative;
		display: flex;
		flex-direction: row;
	  }
	.one-third-column{
			flex: 1;
			text-align: center;
			box-shadow: 0px 3px 1px #333;
			
		}
		
	.one-third-column a{
		color: #333;
		font-weight: bold;
		font-size: 14px;
		display: block;
		padding: 10px 5px;
		background: #eee;
	}
	.mainWrap{
		margin-bottom: 50px;
	}
</style>

</html>

frontend/templates/ordering/ordering_confirm_delete.html
{% extends 'master.html' %}

{% block content %}
<style>
	.btn-warning{
		color: #fff!important;
		background: red!important;
	}
	.btn-link{
		padding: 7px 10px;
		border-radius: 5px;
		border: 1px solid #ccc;
		display : inline-block;
	}
	#delConfirm{
		border: 1px solid red;
		padding: 30px;
		padding-bottom: 10px;
		width: 320px;
		margin: 30px auto;
		margin-bottom: 0px;
	}
	.left-3{
		margin-right: 10px;
	}
</style>
<div class="container" id="delConfirm">
<form method="post">{% csrf_token %}
    <p>"<strong>{{ object }}</strong> မှာထားသည့် ရေမုန့်  <strong>{{object.p_count}}ခု </strong>  ဖျက်မှာသေချာပြီလား"?</p>
    <a href="{% url 'frontend:home' %}" class="btn btn-link left-3" > မဖျက်တော့ပါ </a>
    <input type="submit" class="btn btn-warning" value="သေချာပြီ">
</form>
</div>
{% endblock %}

frontend/templates/ordering/ordering_update_form.html
{% extends 'master.html' %}
{% block content %}

<style>
	.btn-warning{
		color: #fff!important;
		background: red!important;
	}
	.btn-link{
		padding: 7px 10px;
		border-radius: 5px;
		border: 1px solid #ccc;
		display : inline-block;
	}
	#delConfirm{
		border: 1px solid #ccc;
		box-shadow: 0px 1px 5px #ccc;
		padding: 30px;
		padding-bottom: 10px;
		width: 320px;
		margin: 30px auto;
		margin-bottom: 0px;
	}
	.left-3{
		margin-right: 10px;
	}
</style>
<div class="container" id="delConfirm">
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
    <a style="margin-left: 10px;color: red;" href="{% url 'frontend:itemDelete' object.order_id %}" style="color: red;padding: 10x;">ဖျက်ပစ်မယ်</a>
</form>
</div>
{% endblock %}